
import "~/styles/globals.css";
import "@uploadthing/react/styles.css";

import { ClerkProvider } from "@clerk/nextjs";
import { TopNav } from "./_components/topnav";
import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Anselm Long",
  description: "Generated by Anselm",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ 
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${geist.variable} flex-col flex gap-4`}>
        <body>
          <TopNav />
          <main className="overflow-y-scroll">
            <TRPCReactProvider>{children}</TRPCReactProvider>
          </main>
          <div id="modal-root"/>
        </body>
      </html>
    </ClerkProvider>
  );
}
